import rhinoscriptsyntax as rs

line_pattern = [1, -0.25, 0, -0.25, 1, -0.1, 0.25, -0.1]
line_pattern = line_pattern*6
angle1 = 30
base_point1 = [0,1,0]
pat_file1 = [angle1, base_point1, line_pattern]
angle2 = 90
base_point2 = [3,-5,0]
pat_file2 = [angle2, base_point2, line_pattern]


def draw_pattern(pattern, base_point):
    result = []
    offset = 0
    for line in pattern:
        if float(line) > 0:
            result.append(rs.AddLine([base_point[0]+offset,base_point[1],base_point[2]],[base_point[0]+offset+abs(line),base_point[1],base_point[2]]))
            offset = offset+abs(line)
        elif float(line) < 0:
            offset = offset+abs(line)
        else:
            result.append(rs.AddPoint([base_point[0]+offset,base_point[1],base_point[2]]))
    return result
    
def rotate_pattern(pat_file):
    angle = pat_file[0]
    base_point = pat_file[1]
    line_pattern = pat_file[2]
    return rs.RotateObjects(draw_pattern(line_pattern, base_point), base_point, angle, None, True)


line1 = rotate_pattern(pat_file1)
line2 = rotate_pattern(pat_file2)
